version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ajv-errors
    versions:
    - 3.0.0
    - 3.0.0
    - 3.0.0
    - 3.0.0
  - dependency-name: ajv
    versions:
    - 7.2.1
    - 8.0.1
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: agenda
    versions:
    - 4.0.1
    - 4.1.0
  - dependency-name: "@types/convict"
    versions:
    - 6.0.0
  - dependency-name: fastify-metrics
    versions:
    - 7.0.0
  - dependency-name: prom-client
    versions:
    - 13.1.0
  - dependency-name: fastify-swagger
    versions:
    - 4.0.0
