version: '3'
services:
  cep-grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - cep-grafana-storage:/var/lib/grafana
  cep-graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - cep-graphite-storage:/opt/graphite/storage
  cep-mongodb:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - cep-mongodb-storage:/data/db
    ports:
      - 27017:27017
  cep:
    image: francescorivola/tribeca-cep:latest
    environment:
      - MONGODB_URL=mongodb://cep-mongodb:27017
      - HTTP_HOST=0.0.0.0
      - TRIBECA_SCHEDULER_SERVICE_HOST=scheduler
      - TRIBECA_SCHEDULER_SERVICE_PORT=8888
      - INTERNAL_HTTP_HOST=cep
    ports:
      - "8888:8888"
  scheduler:
    image: francescorivola/tribeca-scheduler:latest
    environment:
      - MONGODB_URL=mongodb://cep-mongodb:27017
      - HTTP_HOST=0.0.0.0
volumes:
  cep-grafana-storage:
  cep-graphite-storage:
  cep-mongodb-storage:
