version: '3.2'
services:
  prometheus:
    image: prom/prometheus:v2.19.0
    ports:
        - "9090:9090"
    volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
        - prometheus-storage:/prometheus
    command:
        - "--config.file=/etc/prometheus/prometheus.yaml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention.time=30d"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  mongodb:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb-storage:/data/db
    ports:
      - 27017:27017
  cep:
    image: francescorivola/tribeca-cep:latest
    environment:
      - CEP_MONGODB_URL=mongodb://mongodb:27017
      - CEP_ADMIN_HTTP_HOST=0.0.0.0
      - CEP_EVENT_PROCESSING_HTTP_HOST=0.0.0.0
      - CEP_METRICS_HTTP_HOST=0.0.0.0
      - CEP_ADMIN_HTTP_ENABLE_CORS=true
      - CEP_ADMIN_HTTP_ENABLE_SWAGGER=true
      - CEP_EVENT_PROCESSING_HTTP_ENABLE_SWAGGER=true
    ports:
      - "8888:8888"
      - "8889:8889"
volumes:
  grafana-storage:
  prometheus-storage:
  mongodb-storage:
