version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: "graphite"
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - graphite-storage:/opt/graphite/storage
  tribeca-cep:
    build: .
    container_name: "tribeca-cep"
    ports:
      - "8888:8888"
volumes:
  grafana-storage:
  graphite-storage: