global:
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cep'
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cep:8890']
        labels:
          instance: cep