apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribeca-cep
  namespace: {{ .Values.namespace }}
  labels:
    app: tribeca-cep
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      run: tribeca-cep
  template:
    metadata:
      labels:
        run: tribeca-cep
    spec:
      containers:
      - name: tribeca-cep
        image: {{ .Values.image }}
        readinessProbe:
          httpGet:
            path: /check-health
            port: 3001
            httpHeaders:
            - name: Authorization
              value: "apiKey {{ .Values.deployment.env.adminHttpApiKeys }}"
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
          httpGet:
            path: /check-health
            port: 3001
            httpHeaders:
            - name: Authorization
              value: "apiKey {{ .Values.deployment.env.adminHttpApiKeys }}"
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: "70Mi"
            cpu: "20m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: production
        - name: CEP_EVENT_PROCESSING_HTTP_PORT
          value: "3000"
        - name: CEP_EVENT_PROCESSING_HTTP_HOST
          value: "0.0.0.0"
        - name: CEP_EVENT_PROCESSING_HTTP_ENABLE_SWAGGER
          value: "true"
        - name: CEP_EVENT_PROCESSING_HTTP_TRUST_PROXY
          value: "true"
        - name: CEP_EVENT_PROCESSING_HTTP_BASE_URL
          value: "{{ .Values.deployment.env.eventProcessingHttpBaseUrl }}"
        - name: CEP_ADMIN_HTTP_PORT
          value: "3001"
        - name: CEP_ADMIN_HTTP_HOST
          value: "0.0.0.0"
        - name: CEP_ADMIN_HTTP_ENABLE_SWAGGER
          value: "true"
        - name: CEP_ADMIN_HTTP_ENABLE_CORS
          value: "true"
        - name: CEP_ADMIN_HTTP_TRUST_PROXY
          value: "true"
        - name: CEP_ADMIN_HTTP_API_KEYS
          value: "{{ .Values.deployment.env.adminHttpApiKeys }}"
        - name: CEP_METRICS_HTTP_PORT
          value: "3002"
        - name: CEP_METRICS_HTTP_HOST
          value: "0.0.0.0"
        - name: CEP_MONGODB_URL
          value: mongodb://10.1.1.1:27017