apiVersion: v1
kind: Service
metadata:
  name: tribeca-cep
  labels:
    name: tribeca-cep
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30706
      name: tcp
    - port: 3001
      targetPort: 3001
      name: tcp
  selector:
    run: tribeca-cep