/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventTypesListResponseSchema {
  results: {
    name: string;
    id: string;
    url: string;
    createdAt: string;
    updatedAt: string;
  }[];
  next?: string;
  prev?: string;
}
