name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      CI: true
      SERVICE_NAME: tribeca-cep
      DOCKER_IMAGE: francescorivola/tribeca-cep
      DOCKER_PLATFORMS: linux/x86-64,linux/arm64

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: superchargejs/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run test-ci

    - name: Publish Code Coverage
      if: github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v1

    - name: Set up Docker Buildx
      if: github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-docker-buildx@v3

    - name: Docker Login
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Docker Buildx Build and Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker buildx build --output "type=image,push=true" --platform ${DOCKER_PLATFORMS} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=${GITHUB_SHA::8} \
          --tag ${DOCKER_IMAGE}:sha-$(echo ${{ github.sha }} | cut -c1-7) \
          --tag ${DOCKER_IMAGE}:latest .

    - name: Copy Helm Chart via ssh
      if: github.ref == 'refs/heads/master'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./charts/**"
        target: "./charts/${{ env.SERVICE_NAME }}"
        strip_components: 1
        rm: true

    - name: Deploy using Helm
      if: github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: . ~/.bashrc && helm upgrade ${{ env.SERVICE_NAME }} ./charts/${{ env.SERVICE_NAME }} --set image=${{ env.DOCKER_IMAGE }}:sha-$(echo ${{ github.sha }} | cut -c1-7) --set deployment.env.eventProcessingHttpBaseUrl=${{ secrets.EVENT_PROCESSING_HTTP_BASE_URL}} --set deployment.env.adminHttpApiKeys="${{ secrets.ADMIN_HTTP_API_KEYS }}" --install --wait